/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_spindi_WinPing */

#ifndef _Included_at_spindi_WinPing
#define _Included_at_spindi_WinPing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_spindi_WinPing
 * Method:    native_icmp_WinPing4
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_at_spindi_WinPing_native_1icmp_1WinPing4
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
