/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_spindi_WinPing */

#ifndef _Included_at_spindi_WinPing
#define _Included_at_spindi_WinPing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_spindi_WinPing
 * Method:    native_WinPing_Startup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_spindi_WinPing_native_1WinPing_1Startup
  (JNIEnv *, jclass);

/*
 * Class:     at_spindi_WinPing
 * Method:    native_WinPing_Cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_at_spindi_WinPing_native_1WinPing_1Cleanup
  (JNIEnv *, jclass);

/*
 * Class:     at_spindi_WinPing
 * Method:    native_icmp_WinPing4
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_at_spindi_WinPing_native_1icmp_1WinPing4
  (const JNIEnv *, const jclass, const jint, const jint);

/*
 * Class:     at_spindi_WinPing
 * Method:    native_icmp_WinPing4Async
 * Signature: (IILjava/util/function/Consumer;)I
 */
JNIEXPORT jint JNICALL Java_at_spindi_WinPing_native_1icmp_1WinPing4Async
  (JNIEnv *, const jclass, const jint, const jint, const jobject);

#ifdef __cplusplus
}
#endif
#endif
